# Configuration SMTP pour Gmail
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true

# Identifiants email
email.username=votre.email@gmail.com
email.password=votre-mot-de-passe-d-application

# Activation des notifications (true/false)
email.enabled=false

# Email du gestionnaire par défaut
email.gestionnaire=gestionnaire@univ.edu